### ISSUE TITLE
```aperture_cython``` seems not to be used

### ISSUE THREAD

**Issue by lmether** [PyCOMPLETE/PyHEADTAIL#146]

**Comment by aoeftiger** [comment]
I think it is used in the framework of the simulations by @michuschenk , tbc?

**Comment by michuschenk** [comment]
Hello everyone,

I just had a quick look, it seems indeed that all the functionality that used to be in cython has been moved to the py module. In my opinion the aperture_cython.pyx can hence be removed. Maybe check with Carlo Zannini as well whether he is using the py or the pyx implementation — he did studies with apertures / losses as well.

Cheers,
Michael

**Comment by lmether** [comment]
Module removed in [v1.16.0](https://github.com/PyCOMPLETE/PyHEADTAIL/releases/tag/v1.16.0)
